plugins {
    id 'com.android.application'
}

android {
    namespace 'com.anupcowkur.reservoirsample'
    compileSdk 35

    defaultConfig {
        applicationId 'com.anupcowkur.reservoirsample'
        minSdk 21
        targetSdk 35
        versionName project.VERSION_NAME
        versionCode Integer.parseInt(project.VERSION_CODE)
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['LICENSE.txt']
        }
    }
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.24'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
    }
}

dependencies {
    implementation project(':Library')

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.8'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
}
